/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Birth: typeof import('./src/components/birth.vue')['default']
    FadeInOut: typeof import('./src/components/fadeInOut.vue')['default']
    GverseCheckbox: typeof import('./src/components/gverseCheckbox.vue')['default']
    GverseLoginBtn: typeof import('./src/components/gverseLoginBtn.vue')['default']
    Live: typeof import('./src/components/home/live.vue')['default']
    LoginOrRegisterTitle: typeof import('./src/components/loginOrRegisterTitle.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    MenuPoint: typeof import('./src/components/menuPoint.vue')['default']
    ModuleName: typeof import('./src/components/moduleName.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    News: typeof import('./src/components/home/news.vue')['default']
    NormalInput: typeof import('./src/components/normalInput.vue')['default']
    PasswordInput: typeof import('./src/components/passwordInput.vue')['default']
    RegisterPolicy: typeof import('./src/components/registerPolicy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/searchInput.vue')['default']
    SendSmsCodeBtn: typeof import('./src/components/sendSmsCodeBtn.vue')['default']
    ThemeSelect: typeof import('./src/components/themeSelect.vue')['default']
    Topic: typeof import('./src/components/home/topic.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
